Teste_BRASILAPI/Teste_BRASILAPI/Models/EnderecoModel.cs
using System.Text.Json.Serialization;

namespace Teste_BRASILAPI.Models
{
    public class EnderecoModel
    {
        [JsonPropertyName("cep")]
        public string? Cep { get; set; }

        [JsonPropertyName("state")]
        public string? Estado { get; set; }

        [JsonPropertyName("city")]
        public string? Cidade { get; set; }

        [JsonPropertyName("neighborhood")]
        public string? Região { get; set; }

        [JsonPropertyName("street")]
        public string? Rua { get; set; }

        [JsonPropertyName("service")]
        public string? Servico { get; set; }


        public bool Verificacao { get; set; }
        public string? ErrorMessage { get; set; }

       
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Models/ErrorViewModel.cs
namespace Teste_BRASILAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Models/TempoModel.cs
using System.Text.Json.Serialization;

namespace Teste_BRASILAPI.Models
{
    public class TempoModel
    {
        [JsonPropertyName("Cidade")]
        public string? Cidade { get; set; }

        [JsonPropertyName("Estado")]
        public string? Estado { get; set; }

        [JsonPropertyName("Data de Atualização")]
        public string? AtualizacaoData { get; set; }
        
        [JsonPropertyName("Previsao")]
        public Clima Previsao { get; set; }

        public bool Verificacao { get; set; }
        public string? ErrorMessage { get; set; }
    }

    public class Clima
    {
        [JsonPropertyName("data")]
        public string? Data { get; set; }

        [JsonPropertyName("condicao")]
        public string? Condicao { get; set; }

        [JsonPropertyName("min")]
        public int Min { get; set; }

        [JsonPropertyName("max")]
        public int Max { get; set; }

        [JsonPropertyName("indice_uv")]
        public int IndiceUv { get; set; }

        [JsonPropertyName("condicao_desc")]
        public string? CondicaoDesc { get; set; }
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Mvc;
using Teste_BRASILAPI.Interfaces;
using Teste_BRASILAPI.Services;

namespace Teste_BRASILAPI.Controllers
{
    [ApiController]
    [Route("{controller}")]
    public class EnderecoController : Controller
    {

        private readonly EnderecoService _enderecoService;

        public EnderecoController(EnderecoService enderecoService)
        {
            _enderecoService = enderecoService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet("{action}")]
       
        public async Task<IActionResult> EnderecoInfo(string cep)
        {
            var response = await _enderecoService.BuscarEndereco(cep);

           return View(response);
        }

  
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Teste_BRASILAPI.Models;

namespace Teste_BRASILAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Controllers/TempoController.cs
using Microsoft.AspNetCore.Mvc;
using Teste_BRASILAPI.Services;

namespace Teste_BRASILAPI.Controllers
{
    [ApiController]
    [Route("{controller}")]
    public class TempoController : Controller
    {
        private readonly TempoService _tempoService;

        public TempoController(TempoService tempoService)
        {
            _tempoService = tempoService;
        }

        [HttpGet]   
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("{action}")]
        public async IActionResult BuscarCidade(string cidade)
        {
            var response = await _tempoService.BuscarCidade(cidade);

            return View(response);
        }
    }
}

Teste_BRASILAPI/Teste_BRASILAPI/Views/Endereco/EnderecoInfo.cshtml
@model EnderecoModel



@if(Model.Verificacao)
{

    <div style="height: 100vh; " class=" d-flex flex-column justify-content-start align-items-center pt-5 my-5 text-light  ">
        <h1 class="text-center mb-5"> Segue mais informaçoes sobre o CEP buscado:</h1>

        <form asp-controller="Home" asp-action="EnderecoInfo">
            <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
            justify-content-start  pt-5 pb-4 px-5 rounded">
                <h3 style="color: #051130; font-weight:700;" class="mb-5"> CEP REQUERIDO: <span style="color:white;"> @Model.Cep </span> </h3>
                <p> Estado: <span style="color:#EF6B48; font-weight:600">@Model.Estado</span> </p>
                <p> Cidade: <span style="color:#EF6B48; font-weight:600">@Model.Cidade</span></p>
                <p> Bairro: <span style="color:#EF6B48; font-weight:600">@Model.Região</span></p>
                <p> Rua: <span style="color:#EF6B48; font-weight:600">@Model.Rua</span></p>


                <button asp-controller="Home" asp-action="Index" class="rounded px-4 py-1 text-light mt-4 border-0" style="font-size: 24px;" type="submit"> Voltar </button>

            </div>
        </form>


    </div>
}
else
{
    <h2> @Model.ErrorMessage </h2>
}

Teste_BRASILAPI/Teste_BRASILAPI/Views/Endereco/Index.cshtml
@model EnderecoModel


<div style="height:100vh" ; class="d-flex flex-column align-items-center justify-content-center">

    <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
    justify-content-start p-5 rounded">

        <h1 style="color: #051130; font-weight:600; " class="display-4 mb-3">Buscador de CEP</h1>

        <form method="get" asp-controller="Endereco" asp-action="EnderecoInfo" role="form">

            <input asp-for="Cep" name="cep" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded"  placeholder="Digite seu CEP" />

            <button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit"  value="Cep"> Buscar  </button>
        </form>

    </div>



</div>

Teste_BRASILAPI/Teste_BRASILAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div style="height:100vh"; class="d-flex flex-column align-items-center justify-content-center text-light">

  <h1> Escolha a sua API e divirta-se </h1>

  

</div>

Teste_BRASILAPI/Teste_BRASILAPI/Views/Tempo/CidadeInfo.cshtml
@model TempoModel


<div style="height:100vh" ; class="d-flex flex-column align-items-center justify-content-center">

    <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
    justify-content-start p-5 rounded">

        <h1 style="color: #051130; font-weight:600; " class="display-4 mb-3">Previsão do Tempo</h1>

        <form method="get" asp-controller="Tempo" asp-action="BuscarCidade" role="form">

            <input asp-for="Cidade" name="cidade" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded" placeholder="Digite uma Cidade" />

            <button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit" value="Cep"> Buscar  </button>
        </form>

    </div>

Teste_BRASILAPI/Teste_BRASILAPI/Views/Tempo/Index.cshtml
@model TempoModel


<div style="height:100vh" ; class="d-flex flex-column align-items-center justify-content-center">

    <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
    justify-content-start p-5 rounded">

        <h1 style="color: #051130; font-weight:600; " class="display-4 mb-3">Previsão do Tempo</h1>

        <form method="get" asp-controller="Tempo" asp-action="BuscarCidade" role="form">

            <input asp-for="Cidade" name="cidade" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded" placeholder="Digite uma Cidade" />

            <button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit" value="Cep"> Buscar  </button>
        </form>

    </div>



</div>